name: Elisa Pupko 2
favicon: null
layout_spectrum: 0.1639310212340206
typography_spectrum: 0.6483496376313269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.27119805477559566
  lightness: 0.717107952805236
  saturation: 0.6813897544052452
  rhythmicContrast: 0.07908393675461411
purpose: []
